'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.34209
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Visual_Basic_Themes_By_Sifo_Hamlaoui.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Avast_2014_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Avast_2014_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &apos;/// Theme by DR.SASA on DEV-POINT 
        '''&apos;/// You may use this in any program but you must leave credits
        '''&apos;/// Don&apos;t forget to leave feedback on the thread
        '''
        '''Imports System.Drawing.Text
        '''Imports System.IO
        '''Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''Imports System.ComponentModel.Design
        '''Imports System.Drawing.Design
        '''Imports System.Windows.Forms
        '''
        '''Public Class AVTheme
        '''    Inherits ContainerControl
        '''
        '''    Private C1 As Color = Color.FromArgb(242, 242, 242)
        '''    Private C2 As Color = Color [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Avast2014() As String
            Get
                Return ResourceManager.GetString("Avast2014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bh0_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bh0_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Runtime.InteropServices
        '''Imports System.Collections.Generic
        '''Imports System.Drawing.Drawing2D
        '''Imports System.Drawing.Imaging
        '''Imports System.ComponentModel
        '''Imports System.Windows.Forms
        '''Imports System.Drawing.Text
        '''Imports System.Drawing
        '''Imports System.IO
        '''Imports System
        '''
        '''&apos;-------------------------------------------
        '''&apos; Author           : BILEL BHO
        '''&apos; Created          : 4/10/2013
        '''&apos; Version          : 1.4
        '''&apos; Contact          : http://www.dev-point.com/vb/members/139414.html
        '''&apos; Theme Base  [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property BHO_Theme() As String
            Get
                Return ResourceManager.GetString("BHO_Theme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System, System.IO, System.Collections.Generic, System.Runtime.InteropServices, System.ComponentModel
        '''Imports System.Drawing, System.Drawing.Drawing2D, System.Drawing.Imaging, System.Windows.Forms
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''&apos;--------------------- [ Theme ] --------------------
        '''&apos;Creator: Recuperare
        '''&apos;Contact: cschaefer2183 (Skype)
        '''&apos;Created: 09.22.2012
        '''&apos;Changed: 09.22.2012
        '''&apos;-------------------- [ /Theme ] ---------------------
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property blackshades_net() As String
            Get
                Return ResourceManager.GetString("blackshades_net", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlackShades_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlackShades_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bullion_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bullion_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Drawing2D
        '''
        '''&apos;Creator: Aeonhack
        '''&apos;Date: 8/8/2010
        '''&apos;Site: www.elitevs.net
        '''&apos;Version: 1.0
        '''&apos;This is a modified version of the &quot;FutureTheme&quot;.
        '''
        '''Class BullionTheme
        '''    Inherits Control
        '''
        '''    Protected Overrides Sub OnHandleCreated(ByVal e As EventArgs)
        '''        Dock = DockStyle.Fill
        '''        If TypeOf Parent Is Form Then
        '''            With DirectCast(Parent, Form)
        '''                .FormBorderStyle = 0
        '''                .BackColor = C1
        '''                .ForeColor = Color.FromArgb(170, 170 [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property bullion_theme1() As String
            Get
                Return ResourceManager.GetString("bullion_theme1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Carbon_Fiber_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carbon_Fiber_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &apos;[INFO]
        '''&apos;ThemeBase Creator: Aeonhack
        '''&apos;Site: *********
        '''&apos;[DATE]
        '''&apos;Created: 08/02/2011
        '''&apos;Changed: 12/06/2011
        '''&apos;[VERSION]
        '''&apos;ThemeBase Version: 1.5.4
        '''&apos;
        '''&apos;[INFO]
        '''&apos;Theme Creator: Novi
        '''&apos;Theme Name: CarbonOrainsTheme
        '''&apos;[DATE]
        '''&apos;Created: 7/14/2013
        '''&apos;Changed: 7/26/2013
        '''&apos;Released: 7/27/2013
        '''&apos;[VERSION]
        '''&apos;Version: 1.1
        '''&apos;[CREDITS]
        '''&apos;Thanks to Mavamaarten for the tut =))
        '''&apos;Thanks to Aeonhack for the important ThemeBase154
        '''&apos;--------[/CREDITS]------------
        '''#Region &quot;Imports&quot;
        '''Imports System, System.IO, System.Collect [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property carbonfibretheme() As String
            Get
                Return ResourceManager.GetString("carbonfibretheme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Classic_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Classic_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.ComponentModel, System.Windows.Forms
        '''
        '''&apos;------------------
        '''&apos;Creator: aeonhack
        '''&apos;Theme By: Eprouvez
        '''&apos;Site: elitevs.net
        '''&apos;Created: 8/2/2011
        '''&apos;Changed: 8/31/2011
        '''&apos;Version: 1.5.1
        '''&apos;Released: 9/18/2011
        '''&apos;------------------
        '''
        '''Enum MouseState As Byte
        '''    None = 0
        '''    Over = 1
        '''    Down = 2
        '''    Block = 3
        '''End Enum
        '''
        '''Class Bloom
        '''
        '''    Private _Name As String
        '''    Property Name() As String [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property classic_theme1() As String
            Get
                Return ResourceManager.GetString("classic_theme1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property custom_theme() As String
            Get
                Return ResourceManager.GetString("custom_theme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Effectual_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Effectual_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''&apos;--------------------- [ Theme ] --------------------
        '''&apos;Creator: Mephobia
        '''&apos;Contact: Mephobia.HF (Skype)
        '''&apos;Created: 12.15.2012
        '''&apos;Changed: 12.15.2012
        '''&apos;-------------------- [ /Theme ] ---------------------
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''Enum MouseState As Byte
        '''    None = 0
        '''    Over = 1
        '''    Down = 2
        '''    Block = 3
        '''End Enum
        '''Module Draw
        '''    Public Functio [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Effectual_Theme1() As String
            Get
                Return ResourceManager.GetString("Effectual_Theme1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Electric_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Electric_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à #Region &quot;Comments&quot;
        '''&apos;Classes Theme, ThemeControl, and ThemeContainerControl were created by AeonHack
        '''&apos;   Creator: Aeonhack
        '''&apos;   Date: 4/23/2011
        '''&apos;   Site: ********
        '''&apos;   Version: 1.4
        '''&apos;
        '''&apos;Electric theme created by Hydrogen
        '''&apos;
        '''&apos;Please include my name in the credits if you use this theme in a project
        '''#End Region
        '''
        '''Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''Imports System.Runtime.InteropServices
        '''
        '''MustInherit Class Theme
        '''    Inherits ContainerControl
        '''
        '''#Region &quot; Initialization &quot;
        '''
        '''    Protected G As Gr [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Electric_Theme1() As String
            Get
                Return ResourceManager.GetString("Electric_Theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Text
        '''Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''Imports System.Drawing.Design
        '''
        '''&apos;&apos;&apos; &lt;summary&gt;
        '''&apos;&apos;&apos; Facebook GDI Theme
        '''&apos;&apos;&apos; Creator: Xertz (HF)
        '''&apos;&apos;&apos; Version: 1.1
        '''&apos;&apos;&apos; Date Created: 15/12/2013
        '''&apos;&apos;&apos; Date Changed: 15/12/2013
        '''&apos;&apos;&apos; UID: 1602992
        '''&apos;&apos;&apos; For any bugs / errors, PM me.
        '''&apos;&apos;&apos; &lt;/summary&gt;
        '''&apos;&apos;&apos; &lt;remarks&gt;&lt;/remarks&gt;
        '''
        '''Module DrawHelpers
        '''
        '''#Region &quot;Functions&quot;
        '''
        '''    Dim Height As Integer
        '''    Dim Width As Integer
        '''
        '''    Public Function RoundRec(ByVal Rectangle As [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Facebook() As String
            Get
                Return ResourceManager.GetString("Facebook", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Facebook_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Facebook_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Flut_ui_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flut_ui_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Drawing2D, System.ComponentModel, System.Windows.Forms
        '''
        '''&apos;&apos;&apos; &lt;summary&gt;
        '''&apos;&apos;&apos; Flat UI Theme
        '''&apos;&apos;&apos; Creator: iSynthesis (HF)
        '''&apos;&apos;&apos; Version: 1.0.4
        '''&apos;&apos;&apos; Date Created: 17/06/2013
        '''&apos;&apos;&apos; Date Changed: 26/06/2013
        '''&apos;&apos;&apos; UID: 374648
        '''&apos;&apos;&apos; For any bugs / errors, PM me.
        '''&apos;&apos;&apos; &lt;/summary&gt;
        '''&apos;&apos;&apos; &lt;remarks&gt;&lt;/remarks&gt;
        '''
        '''Module Helpers
        '''
        '''#Region &quot; Variables&quot;
        '''    Friend G As Graphics, B As Bitmap
        '''    Friend _FlatColor As Color = Color.FromArgb(211, 211, 211)
        '''    Friend NearSF As New StringFormat() With {.Al [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property flut_ui_theme1() As String
            Get
                Return ResourceManager.GetString("flut_ui_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System, System.IO, System.Collections.Generic, System.Runtime.InteropServices, System.ComponentModel
        '''Imports System.Drawing, System.Drawing.Drawing2D, System.Drawing.Imaging, System.Windows.Forms
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''&apos;--------------------- [ Credits ] --------------------
        '''&apos;Creator: Recuperare
        '''&apos;Contact: cschaefer2183 (Skype)
        '''&apos;Created: 10.11.2012
        '''&apos;Changed: 10.11.2012
        '''&apos;-------------------- [ /Credits ] ---------------------
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property influence_theme() As String
            Get
                Return ResourceManager.GetString("influence_theme", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Influx_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Influx_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Option Strict On
        '''
        '''Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.ComponentModel, System.Windows.Forms
        '''Imports System.Runtime.InteropServices
        '''Imports System.Drawing.Imaging
        '''Imports System.Reflection
        '''
        '''&apos;########|CREDITS|##########
        '''&apos;# Theme: Blink            #
        '''&apos;# Themebase: Aeonhack     #
        '''&apos;###########################
        '''&apos;# Other: Mavamaarten~     #
        '''&apos;# Controls based on his   #
        '''&apos;###########################
        '''
        '''&apos;##########|INFO|#### [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property influx_theme1() As String
            Get
                Return ResourceManager.GetString("influx_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Inluence_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inluence_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à &apos;
        '''&apos; * Kaspersky 2014 Theme 
        '''&apos; * v1.0.0.0
        '''&apos; * by Guilherme Santos
        '''&apos; * guilhermesantos97@live.com
        '''&apos; 
        '''
        '''
        '''Imports System.Collections.Generic
        '''Imports System.Drawing
        '''Imports System.Drawing.Drawing2D
        '''Imports System.Runtime.InteropServices
        '''Imports System.Text
        '''Imports System.Windows.Forms
        '''
        '''Namespace Themes_CSharp
        '''	Public Class Kaspersky2014Form
        '''		Inherits Form
        '''
        '''		Protected Const WM_NCLBUTTONDOWN As Integer = &amp;Ha1
        '''		Protected Const HT_CAPTION As Integer = &amp;H2
        '''
        '''		&lt;DllImport(&quot;user32.dll&quot;)&gt; _
        '''		Pri [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property kaspersky() As String
            Get
                Return ResourceManager.GetString("kaspersky", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KasperSky_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KasperSky_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LogIn_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogIn_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Option Strict On
        '''
        '''Imports System.Drawing.Text
        '''Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''
        '''&apos;&apos;     DO NOT REMOVE CREDITS! IF YOU USE PLEASE CREDIT!     &apos;&apos;
        '''
        '''&apos;&apos;&apos; &lt;summary&gt;
        '''&apos;&apos;&apos; LogIn GDI+ Theme
        '''&apos;&apos;&apos; Creator: Xertz (HF)
        '''&apos;&apos;&apos; Version: 1.3
        '''&apos;&apos;&apos; Control Count: 28
        '''&apos;&apos;&apos; Date Created: 18/12/2013
        '''&apos;&apos;&apos; Date Changed: 23/04/2014
        '''&apos;&apos;&apos; UID: 1602992
        '''&apos;&apos;&apos; For any bugs / errors, PM me.
        '''&apos;&apos;&apos; &lt;/summary&gt;
        '''&apos;&apos;&apos; &lt;remarks&gt;&lt;/remarks&gt;
        '''
        '''Module DrawHelpers
        '''
        '''#Region &quot;Functions&quot;
        '''
        '''    Public Function RoundR [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Login_Theme1() As String
            Get
                Return ResourceManager.GetString("Login_Theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Meph_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Meph_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''&apos;--------------------- [ Theme ] --------------------
        '''&apos;Creator: Mephobia
        '''&apos;Contact: Mephobia.HF (Skype)
        '''&apos;Created: 4.20.2013
        '''&apos;Changed: 4.20.2013
        '''&apos;-------------------- [ /Theme ] ---------------------
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''Enum MouseState As Byte
        '''    None = 0
        '''    Over = 1
        '''    Down = 2
        '''    Block = 3
        '''End Enum
        '''Module Draw
        '''    Public Function  [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property meph_theme1() As String
            Get
                Return ResourceManager.GetString("meph_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nyx_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nyx_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à #Region &quot;Themebase&quot;
        '''Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.ComponentModel, System.Windows.Forms
        '''Imports System.Runtime.InteropServices
        '''Imports System.Drawing.Imaging
        '''Imports System.Drawing.Design
        '''
        '''&apos;------------------
        '''&apos;Creator: Aeonhack
        '''&apos;Site: elitevs.net
        '''&apos;Created: 08/02/2011
        '''&apos;Changed: 12/06/2011
        '''&apos;Version: 1.5.4
        '''&apos;------------------
        '''
        '''MustInherit Class ThemeContainer154
        '''    Inherits ContainerControl
        '''
        '''#Region &quot; Ini [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property nyx_theme1() As String
            Get
                Return ResourceManager.GetString("nyx_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Orains_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Orains_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à &apos;------------------
        '''&apos;Theme: OrainsTheme
        '''&apos;Site: hackforums.net
        '''&apos;Created: 06/12/2013
        '''&apos;Changed: 06/15/2013
        '''&apos;Version: 1.0
        '''&apos;------------------
        '''
        '''
        '''#Region &quot;ThemeBase154&quot;
        '''Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.ComponentModel, System.Windows.Forms
        '''Imports System.Runtime.InteropServices
        '''Imports System.Drawing.Imaging
        '''Imports System.Windows.Forms.TabControl
        '''Imports System.ComponentModel.Design
        '''&apos;------------------
        '''&apos;Creator: [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property orainstheme() As String
            Get
                Return ResourceManager.GetString("orainstheme", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Origin_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Origin_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à #Region &quot;ThemeBase&quot;
        '''Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.ComponentModel, System.Windows.Forms
        '''Imports System.Runtime.InteropServices
        '''Imports System.Drawing.Imaging
        '''
        '''&apos;------------------
        '''&apos;Creator: aeonhack
        '''&apos;Site: elitevs.net
        '''&apos;Created: 08/02/2011
        '''&apos;Changed: 12/06/2011
        '''&apos;Version: 1.5.4
        '''&apos;------------------
        '''
        '''MustInherit Class ThemeContainer154
        '''    Inherits ContainerControl
        '''
        '''#Region &quot; Initialization &quot;
        '''
        '''    Protected  [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property origin_theme1() As String
            Get
                Return ResourceManager.GetString("origin_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paladin_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paladin_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.ComponentModel, System.Windows.Forms
        '''Imports System.Runtime.InteropServices
        '''Imports System.Drawing.Imaging
        '''
        '''
        '''#Region &quot;Bases&quot;
        '''
        '''
        '''MustInherit Class ThemeContainer154
        '''    Inherits ContainerControl
        '''
        '''#Region &quot; Initialization &quot;
        '''
        '''    Protected G As Graphics, B As Bitmap
        '''
        '''    Sub New()
        '''        SetStyle(DirectCast(139270, ControlStyles), True)
        '''
        '''        _ImageSize = Size.Empty
        '''     [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property paladin_theme1() As String
            Get
                Return ResourceManager.GetString("paladin_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PerPlex_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PerPlex_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''&apos;--------------------- [ Theme ] --------------------
        '''&apos;Creator: Mephobia
        '''&apos;Contact: Mephobia.HF (Skype)
        '''&apos;Created: 10.27.2012
        '''&apos;Changed: 10.27.2012
        '''&apos;-------------------- [ /Theme ] ---------------------
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''Enum MouseState As Byte
        '''    None = 0
        '''    Over = 1
        '''    Down = 2
        '''    Block = 3
        '''End Enum
        '''Module Draw
        '''    Public Functio [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property perplex_theme1() As String
            Get
                Return ResourceManager.GetString("perplex_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Positron_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Positron_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à #Region &quot;ThemeBase&quot;
        '''Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.ComponentModel, System.Windows.Forms
        '''Imports System.Runtime.InteropServices
        '''Imports System.Drawing.Imaging
        '''
        '''&apos;------------------
        '''&apos;Creator: aeonhack
        '''&apos;Site: elitevs.net
        '''&apos;Created: 08/02/2011
        '''&apos;Changed: 12/06/2011
        '''&apos;Version: 1.5.4
        '''&apos;------------------
        '''
        '''MustInherit Class ThemeContainer154
        '''    Inherits ContainerControl
        '''
        '''#Region &quot; Initialization &quot;
        '''
        '''    Protected  [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property positron_theme1() As String
            Get
                Return ResourceManager.GetString("positron_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Purityx_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Purityx_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à &apos;Creator: Slurms Makenzi
        '''&apos;Thanks Aeon for theme class!
        '''&apos;Date: 7/7/2011
        '''&apos;Site: www.loungeforum.net
        '''&apos;Version: 1.0
        '''&apos;Thanks xZ3ROxPROJ3CTx
        '''
        '''&apos;
        '''
        '''&apos;\\\\\\\\\\\\\\\Use Credits Were Credits Are Needed///////////////////
        '''
        '''&apos;
        '''
        '''#Region &quot;Imports&quot;
        '''Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''Imports System.Runtime.InteropServices
        '''#End Region
        '''MustInherit Class Theme
        '''    Inherits ContainerControl
        '''
        '''#Region &quot; Initialization &quot;
        '''
        '''    Protected G As Graphics
        '''    Sub New()
        '''        SetStyle [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property purityx_theme1() As String
            Get
                Return ResourceManager.GetString("purityx_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Reactor_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reactor_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System, System.Collections.Generic, System.Runtime.InteropServices, System.ComponentModel
        '''Imports System.Drawing, System.Drawing.Drawing2D, System.Drawing.Imaging, System.Windows.Forms
        '''
        '''Enum MouseState As Byte
        '''    None = 0
        '''    Over = 1
        '''    Down = 2
        '''    Block = 3
        '''End Enum
        '''
        '''
        '''&apos;--------------------- [ Theme ] --------------------
        '''&apos;Creator: oVERT3Xo
        '''&apos;Site: **********.net
        '''&apos;Contact: oVERT3Xo@hotmail.com
        '''&apos;Created: 11/22/2011
        '''&apos;Changed: 11/23/2011
        '''&apos;-------------------- [ /Theme ] ------------ [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property reactor_theme1() As String
            Get
                Return ResourceManager.GetString("reactor_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Recon_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Recon_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''Imports System.Runtime.InteropServices
        '''&apos;.::Tweety Theme::.
        '''&apos;Author:   UnReLaTeDScript
        '''&apos;Credits:  Aeonhack [Themebase], Aeonhack (Menustrip Code)
        '''&apos;Version:  1.0
        '''MustInherit Class Theme
        '''    Inherits ContainerControl
        '''
        '''#Region &quot; Initialization &quot;
        '''
        '''    Protected G As Graphics
        '''    Sub New()
        '''        SetStyle(DirectCast(139270, ControlStyles), True)
        '''    End Sub
        '''
        '''    Private ParentIsForm As Boolean
        '''    Protected Overrides Sub OnHandleCre [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property recon_theme1() As String
            Get
                Return ResourceManager.GetString("recon_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property recuperareii_theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recuperareii_theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System, System.IO, System.Collections.Generic, System.Runtime.InteropServices, System.ComponentModel
        '''Imports System.Drawing, System.Drawing.Drawing2D, System.Drawing.Imaging, System.Windows.Forms
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''&apos;--------------------- [ Theme ] --------------------
        '''&apos;Creator: Recuperare
        '''&apos;Contact: cschaefer2183 (Skype)
        '''&apos;Created: 01.02.2012
        '''&apos;Changed: 01.02.2012
        '''&apos;-------------------- [ /Theme ] ---------------------
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property recuperareii_theme1() As String
            Get
                Return ResourceManager.GetString("recuperareii_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Redemption_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Redemption_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Drawing2D, System.Drawing.Text, System.Drawing
        '''Imports System.ComponentModel
        '''
        '''Public Enum MouseState As Byte
        '''    None = 0
        '''    Over = 1
        '''    Down = 2
        '''End Enum
        '''
        '''Module Draw
        '''    Public Function RoundRect(ByVal Rectangle As Rectangle, ByVal Curve As Integer) As GraphicsPath
        '''        Dim P As GraphicsPath = New GraphicsPath()
        '''        Dim ArcRectangleWidth As Integer = Curve * 2
        '''        P.AddArc(New Rectangle(Rectangle.X, Rectangle.Y, ArcRectangleWidth, ArcRectangleWidth), -180,  [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property redemption_theme1() As String
            Get
                Return ResourceManager.GetString("redemption_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rockstar_theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rockstar_theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à &apos;Creator: Slurms Makenzi
        '''&apos;Thanks: Aeon and xZ3ROxPROJ3CTx
        '''
        '''Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''Imports System.Runtime.InteropServices
        '''
        '''MustInherit Class Theme
        '''    Inherits ContainerControl
        '''
        '''#Region &quot; Initialization &quot;
        '''
        '''    Protected G As Graphics
        '''    Sub New()
        '''        SetStyle(DirectCast(139270, ControlStyles), True)
        '''    End Sub
        '''
        '''    Private ParentIsForm As Boolean
        '''    Protected Overrides Sub OnHandleCreated(ByVal e As EventArgs)
        '''        Dock = DockStyle.Fill
        '''        ParentIsForm = [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Rockstar_Theme1() As String
            Get
                Return ResourceManager.GetString("Rockstar_Theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sharp_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sharp_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.ComponentModel, System.Drawing, System.Drawing.Drawing2D
        '''Enum MouseState As Byte
        '''    None = 0
        '''    Over = 1
        '''    Down = 2
        '''    Block = 3
        '''End Enum
        '''
        '''Class SharpButton
        '''
        '''    Inherits Control
        '''
        '''#Region &quot; Control Help - MouseState &amp; Flicker Control&quot;
        '''    Private State As MouseState = MouseState.None
        '''    Protected Overrides Sub OnMouseEnter(ByVal e As System.EventArgs)
        '''        MyBase.OnMouseEnter(e)
        '''        State = MouseState.Over
        '''        Invalidate()
        '''    End Sub
        '''    Protected Override [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property sharp_theme1() As String
            Get
                Return ResourceManager.GetString("sharp_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skype_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skype_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.ComponentModel, System.Windows.Forms
        '''Imports System.Runtime.InteropServices
        '''Imports System.Drawing.Imaging
        '''
        '''&apos;------------------
        '''&apos;Creator: aeonhack
        '''&apos;Site: *****
        '''&apos;Created: 08/02/2011
        '''&apos;Changed: 12/06/2011
        '''&apos;Version: 1.5.4
        '''&apos;------------------
        '''
        '''MustInherit Class ThemeContainer154
        '''    Inherits ContainerControl
        '''
        '''#Region &quot; Initialization &quot;
        '''
        '''    Protected G As Graphics, B As Bitmap
        ''' [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Skype_Theme1() As String
            Get
                Return ResourceManager.GetString("Skype_Theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Slc_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Slc_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à &apos;IMPORTANT:
        '''&apos;Please leave these comments in place as they help protect intellectual rights and allow
        '''&apos;developers to determine the version of the theme they are using. 
        '''&apos;Name: SLC Theme
        '''&apos;Created: Not defined yet
        '''&apos;Version: 1.0.0.0 beta
        '''&apos;Site: http://sliceproducts.pw/
        '''
        '''&apos;Copyright © 2013 Slice Software
        '''&apos;Special Thanks to : Aeonhack http://nimoru.com/
        '''
        '''
        '''#Region &quot;Theme Container&quot;
        '''Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.Co [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property slc_theme1() As String
            Get
                Return ResourceManager.GetString("slc_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sugar_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sugar_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à 
        '''&apos; ####### Sugar Theme #######
        '''
        '''&apos;Theme name: Sugar Theme
        '''&apos;Creator   : greenviruz
        '''&apos;SKYPE     : greenviruz
        '''&apos;Site:     : www.aeonsofts.com
        '''&apos;Created   : 26/07/2012
        '''&apos;Version   : 1.0
        '''&apos;Thanks to : aeonhack ,Mavamaarten
        '''&apos;If you want a custom theme to be designed contact me at my skype..
        '''&apos;IF YOU ARE USING THIS THEME GIVE CREDITS TO ME
        '''&apos;THIS THEME IS A FREE THEME
        '''
        '''&apos;####### Sugar Theme #######
        '''
        '''
        '''#Region &quot;Themebase&quot;
        '''Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System. [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property sugar_theme1() As String
            Get
                Return ResourceManager.GetString("sugar_theme1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''
        '''Public Class ThirteenForm : Inherits ContainerControl
        '''    Enum ColorSchemes
        '''        Light
        '''        Dark
        '''    End Enum
        '''    Event ColorSchemeChanged()
        '''    Private _ColorScheme As ColorSchemes
        '''    Public Property ColorScheme() As ColorSchemes
        '''        Get
        '''            Return _ColorScheme
        '''        End Get
        '''        Set(ByVal value As ColorSchemes)
        '''            _ColorScheme = value
        '''            RaiseEvent ColorSchemeChanged()
        '''        End Set [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property teen_theme() As String
            Get
                Return ResourceManager.GetString("teen_theme", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thirteen_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thirteen_Theme", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Recherche une chaîne localisée semblable à &apos;------------------
        '''&apos;Creator: Tidas
        '''&apos;Created: 06/22/2013
        '''&apos;Changed: 06/22/2013
        '''&apos;Version: 1.0.0
        '''&apos;Credits: 
        '''&apos; • Aeonhack ~ Themebase
        '''&apos; • Mavamaarten ~ Textbox + Tutorials
        '''&apos; • xZ3ROxPROJ3CTx ~ General Help, Control Box, Progress Bar.
        '''&apos;------------------
        '''
        '''#Region &quot;Themebase&quot;
        '''Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.ComponentModel, System.Windows.Forms
        '''Imports System.Runtime.InteropServices
        '''Imports System.Drawing.Imaging
        ''' [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property twitch_theme() As String
            Get
                Return ResourceManager.GetString("twitch_theme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Twitch_White_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Twitch_White_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ubuntu_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ubuntu_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.ComponentModel
        '''Imports System.Drawing.Drawing2D
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''&apos;--------------------- [ Theme ] --------------------
        '''&apos;Creator: Mephobia
        '''&apos;Contact: Mephobia.HF (Skype)
        '''&apos;Created: 10.10.2012
        '''&apos;Changed: 10.10.2012
        '''&apos;-------------------- [ /Theme ] ---------------------
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''Enum MouseState As Byte
        '''    None = 0
        '''    Over = 1
        '''    Down = 2
        '''    Block = 3
        '''End Enum
        '''
        '''Module Draw
        '''    Public Funct [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property ubuntu_theme1() As String
            Get
                Return ResourceManager.GetString("ubuntu_theme1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''Imports System.Runtime.InteropServices
        '''&apos;.::VibeLander Theme::.
        '''&apos;Author:   UnReLaTeDScript
        '''&apos;Credits:  Aeonhack [Themebase]
        '''&apos;Version:  1.0
        '''MustInherit Class Theme
        '''    Inherits ContainerControl
        '''
        '''#Region &quot; Initialization &quot;
        '''
        '''    Protected G As Graphics
        '''    Sub New()
        '''        SetStyle(DirectCast(139270, ControlStyles), True)
        '''    End Sub
        '''
        '''    Private ParentIsForm As Boolean
        '''    Protected Overrides Sub OnHandleCreated(ByVal e As EventAr [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property vibelander_theme() As String
            Get
                Return ResourceManager.GetString("vibelander_theme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Viblender_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Viblender_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Visceral_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Visceral_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''
        '''Enum MouseState As Byte
        '''    None = 0
        '''    Over = 1
        '''    Down = 2
        '''    Block = 3
        '''End Enum
        '''
        '''Module Draw
        '''    Public Function RoundRect(ByVal Rectangle As Rectangle, ByVal Curve As Integer) As GraphicsPath
        '''        Dim P As GraphicsPath = New GraphicsPath()
        '''        Dim ArcRectangleWidth As Integer = Curve * 2
        '''        P.AddArc(New Rectangle(Rectangle.X, Rectangle.Y, ArcRectangleWidth, ArcRectangleWidth), -180, 90)
        '''        P.AddArc(New Rec [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property visceral_theme1() As String
            Get
                Return ResourceManager.GetString("visceral_theme1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VIT_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VIT_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vitality_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vitality_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à #Region &quot;Themebase&quot;
        '''Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.ComponentModel, System.Windows.Forms
        '''Imports System.Runtime.InteropServices
        '''Imports System.Drawing.Imaging
        '''
        '''&apos;------------------
        '''&apos;Creator: aeonhack
        '''&apos;Site: elitevs.net
        '''&apos;Created: 08/02/2011
        '''&apos;Changed: 12/06/2011
        '''&apos;Version: 1.5.4
        '''&apos;------------------
        '''
        '''MustInherit Class ThemeContainer154
        '''    Inherits ContainerControl
        '''
        '''#Region &quot; Initialization &quot;
        '''
        '''    Protected  [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property vitality_theme1() As String
            Get
                Return ResourceManager.GetString("vitality_theme1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Win8_Theme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Win8_Theme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 
        '''Imports System, System.IO, System.Collections.Generic
        '''Imports System.Drawing, System.Drawing.Drawing2D
        '''Imports System.ComponentModel, System.Windows.Forms
        '''Class WinEightTheme
        '''    Inherits ThemeContainer151
        '''    Private C1, C2, C3 As Color
        '''    Private B1 As SolidBrush
        '''    Private P1, P2 As Pen
        '''    Sub New()
        '''        MoveHeight = 20
        '''        SetColor(&quot;BackColor&quot;, Color.White)
        '''        TransparencyKey = Color.Fuchsia
        '''    End Sub
        '''    Protected Overrides Sub ColorHook()
        '''        C1 = GetColor(&quot;BackCol [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property windows_8() As String
            Get
                Return ResourceManager.GetString("windows_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property X_Visual() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("X_Visual", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Imports System.Drawing.Drawing2D
        '''Imports System.ComponentModel
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''&apos;--------------------- [ Theme ] --------------------
        '''&apos;Creator: Mephobia
        '''&apos;Contact: Mephobia.HF (Skype)
        '''&apos;Created: 6.19.2013
        '''&apos;Changed: 6.19.2013
        '''&apos;-------------------- [ /Theme ] ---------------------
        '''
        '''&apos;PLEASE LEAVE CREDITS IN SOURCE, DO NOT REDISTRIBUTE!
        '''
        '''Enum MouseState As Byte
        '''    None = 0
        '''    Over = 1
        '''    Down = 2
        '''    Block = 3
        '''End Enum
        '''Module Draw
        '''    Public Function  [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property xvisual_theme_() As String
            Get
                Return ResourceManager.GetString("xvisual_theme_", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
